### ISSUE TITLE
No need to search entire runfolder for fastq files

### ISSUE THREAD

**Issue by johandahlberg** [Molmed/sisyphus#123]
At: https://github.com/Molmed/sisyphus/blob/master/quickReport.pl#L125 the entire runfolder is searched for the fastq files - which takes a non-neglected amount of time. Since we know that fastq files will only be available in part of the runfolder, typically under `Unaligned`, maybe we could just search that?

**Comment by MatildaAslin** [comment]
Yes, I think that's a good idea. I can not think of any scenario where the fastqs would be anywhere else.

**Comment by MatildaAslin** [comment]
Fixed in #125
