### ISSUE TITLE
Automatisera sisyphus

### ISSUE THREAD

**Issue by Smeds** [Molmed/sisyphus#3]
SampleSheet-rutin
*Namngivning instruktion
*Sisyphus ska kopiera samplesheet och sisyphus.yml

Cron-job: 
*Skickas från biotank
*kontrollera att RTAComplete.txt finns

Skript för att kontrollera QC-kritier
*Sisyphus ska inte rsync innan godkänt QC 
*Vi ok start aeacus-report.pl 
*Annars skicka mail 

Vid Error skicka mail

batch ska skicka mail vid Error och Arkiveringsjobbet och ska skicka mail vid success. Arkiveringsvalideringen ska skicka mail vid både success och Error,

Uppdatera Sisyphus

**Comment by MatildaAslin** [comment]
This is sort of done, right, @Smeds ?
