### ISSUE TITLE
Remove "sleep" functionalities in Sisyphus

### ISSUE THREAD

**Issue by MatildaAslin** [Molmed/sisyphus#93]
There are several events that trigger Sisyphus to sleep, e.g. not using the -nowait flag and incorrect samplesheet. 

I think these sleep functionalities should be removed since they are not helpful. The latter example can actually be devastating since Hercules can end up in an endless loop, waiting for a new SampleSheet. Since there are no error, Hercules will not notify us about this and the "demultiplexing in progress" status will remain.

**Comment by johandahlberg** [comment]
Good catch!

**Comment by MatildaAslin** [comment]
Fixed in #122. The nowait flag remains though, changing it would require an update of Hercules, so I decided to keep it for now.
